name: Embedded CI Pipeline

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile Tests
        run: |
          gcc -I./shared_components/include \
              -I./shared_components/unity \
              ./shared_components/src/payload_parser.c \
              ./shared_components/unity/unity.c \
              ./shared_components/tests/test_payload_parser.c \
              -o test_run

      - name: Run Unit Tests
        run: ./test_run 