name: Embedded CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/zigbee_network]
  pull_request:
    branches: [ main, develop ]

jobs:
  # 1. Fast Host-Side Unit Tests
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Install GCC & Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile Tests
        run: |
          gcc -I./shared_components/include \
              -I./shared_components/unity \
              ./shared_components/src/payload_parser.c \
              ./shared_components/unity/unity.c \
              ./shared_components/tests/test_payload_parser.c \
              -o test_run

      - name: Run Unit Tests
        run: ./test_run 

  # 2. Parallel nRF Connect SDK Firmware Compilation
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-latest
    needs: run-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - app-name: "Network Coordinator"
            app-path: "zigbee_network/network_coordinator"
            sysbuild: true
          - app-name: "Light Switch"
            app-path: "zigbee_end_device/light_switch"
            sysbuild: true
          - app-name: "BMP180 Application"
            app-path: "zigbee_end_device/bmp180"
            sysbuild: false

    # Using the prebuilt NCS v2.9 docker container containing the GCC-ARM toolchain and Zephyr dependencies
    container:
      image: nordicplayground/nrfconnect-sdk:v2.9-branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: project # Checkout project in a subdirectory to avoid conflicting with the container's SDK files

      - name: Initialize CCache
        uses: actions/cache@v4
        with:
          path: /root/.cache/ccache
          key: ccache-${{ matrix.app-path }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.app-path }}-

      - name: Build Firmware (Sysbuild)
        if: ${{ matrix.sysbuild == true }}
        run: |
          nrfutil toolchain-manager launch -- west build -b nrf52840dk/nrf52840 -s project/${{ matrix.app-path }} -d project/${{ matrix.app-path }}/build --sysbuild

      - name: Build Firmware (Standard)
        if: ${{ matrix.sysbuild == false }}
        run: |
          nrfutil toolchain-manager launch -- west build -b nrf52840dk/nrf52840 -s project/${{ matrix.app-path }} -d project/${{ matrix.app-path }}/build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app-name }}-firmware
          path: |
            project/${{ matrix.app-path }}/build/**/zephyr.hex
            project/${{ matrix.app-path }}/build/**/zephyr.bin
            project/${{ matrix.app-path }}/build/**/zephyr.elf